services:
  postgres:
    image: postgres:16-alpine
    container_name: resto_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-restaurant_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-restaurant_secret_password}
      POSTGRES_DB: ${POSTGRES_DB:-restaurant_platform}
    ports:
      - "${DB_PORT:-5435}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-restaurant_user} -d ${POSTGRES_DB:-restaurant_platform}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - resto_net

  redis:
    image: redis:7-alpine
    container_name: resto_redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6381}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - resto_net

  mailpit:
    image: axllent/mailpit:latest
    container_name: resto_mailpit
    restart: unless-stopped
    ports:
      - "${MAILPIT_SMTP_PORT:-1025}:1025"
      - "${MAILPIT_DASHBOARD_PORT:-8025}:8025"
    networks:
      - resto_net

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: resto_api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: "postgresql://${POSTGRES_USER:-restaurant_user}:${POSTGRES_PASSWORD:-restaurant_secret_password}@postgres:5432/${POSTGRES_DB:-restaurant_platform}?schema=public"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      FRONTEND_URL: "http://localhost:${WEB_PORT:-3001}"
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET:-secret_jwt_access_dev_min_32_chars}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-secret_jwt_refresh_dev_min_32_chars}
      COOKIE_SECRET: ${COOKIE_SECRET:-secret_cookie_dev_min_32_chars}
      STORAGE_PROVIDER: local
      UPLOAD_DIR: /app/uploads
      INVOICE_PROVIDER: fake
    ports:
      - "${API_PORT:-4000}:4000"
    volumes:
      - media_data:/app/uploads
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:4000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - resto_net

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    container_name: resto_web
    restart: unless-stopped
    depends_on:
      - api
    environment:
      NODE_ENV: production
      PORT: 3001
      NEXT_PUBLIC_API_URL: "http://localhost:${API_PORT:-4000}"
      NEXT_PUBLIC_SOCKET_URL: "http://localhost:${API_PORT:-4000}"
    ports:
      - "${WEB_PORT:-3001}:3001"
    networks:
      - resto_net

volumes:
  postgres_data:
  redis_data:
  media_data:

networks:
  resto_net:
    driver: bridge
